### PR TITLE
[provider] fix subscriptions

### LINKED ISSUE #338: How to work with `provider.subscribe`
I could not find any tests for it, and when I tried to implement a for `author_submitAndWatchExtrinsic` I noticed that I don't get any events in my subscriptions. I also tried to get events for `chain_subscribeFinalizedHeads`.

May I ask for help please? This is the commit I am trying to fix: https://github.com/encointer/encointer-wallet-flutter/commit/1f15d2d64c152b6cda96b0c0236b2fda462aec54

### PR DESCRIPTION
**Pull request by clangenb**
Closes #338. So the problem is that the method name returned in subscription names doesn't match the method name that is used to actually subscribe; hence we were unable to get the correct stream controller in the subscription messages. This PR fixes it in a way that we introduce a map that uses purely the subscription ID, to identify the stream controller.

### CODE REVIEW

File: packages/polkadart/lib/provider.dart [hunk 1]
```diff
@@ -186,23 +188,22 @@ class WsProvider extends Provider {
...
     // Subscriptions
-    jsonStream
-        .where((message) =>
-            !message.containsKey('id') &&
-            message.containsKey('params') &&
-            (message['params'] as Map<String, dynamic>)
-                .containsKey('subscription'))
-        .map((message) {
+    jsonStream.where((message) {
+      // print('Received stream msg: $message');
```
Comment (clangenb) [inline packages/polkadart/lib/provider.dart:192]: I found my prints quite useful for debugging so I left them here for now. I am from the rust domain initially, and I wonder how idiomatic dart logging is done? Happy to introduce proper logging here if you advise me how you would like to do it.

File: packages/polkadart/lib/provider.dart [hunk 2]
```diff
@@ -251,7 +250,13 @@ class WsProvider extends Provider {
   @override
   Future<SubscriptionReponse> subscribe(String method, List<dynamic> params,
       {FutureOr<void> Function(String subscription)? onCancel}) async {
+    // print('Subscribing to method: $method');
     final result = await send(method, params);
+
+    if (result.error != null) {
+      throw Exception(result.error.toString());
+    }
```
Comment (clangenb) [inline packages/polkadart/lib/provider.dart:258]: Handle errors that can happen during subscribing, like subscribing in `author_submitAndWatchExtrinsic` with an invalid signature.

**Comment by clangenb** [comment]
@leonardocustodio happy to receive your feedback here.

File: packages/polkadart/lib/provider.dart [hunk 3]
```diff
@@ -186,23 +188,22 @@ class WsProvider extends Provider {
...
+      // print('Received stream msg: $message');
+      final valid =
+          !message.containsKey('id') && message.containsKey('params') && (message['params'] as Map<String, dynamic>).containsKey('subscription');
+      return valid;
+    }).map((message) {
       final method = message['method'] as String;
       final params = message['params'] as Map<String, dynamic>;
       final subscription = params['subscription'] as String;
-      final result = params.containsKey('result') ? message['result'] : null;
+      final result = params.containsKey('result') ? params['result'] : null;
```
Comment (clangenb) [inline packages/polkadart/lib/provider.dart:200]: Another necessary tiny fix to make it work.

**Comment by leonardocustodio** [comment]
Hey, that's great, though I had noticed this issue last week I'm still finishing up the extrinsic signing that also has an issue. I'm glad you fixed. I can review it during the day. Thanks 😄

File: packages/polkadart/lib/provider.dart (hunk 1 above)
Comment (leonardocustodio) [reply packages/polkadart/lib/provider.dart:192]: This package is pretty good for logging in dart, if you want to go ahead: https://pub.dev/packages/logger

**Review by leonardocustodio — COMMENTED** [review]
The previous implementation supposed that a `subscriptionId` was unique only within each `method` but that seems to be incorrect and they are unique globally. Do you think we could simplify that and remove the `Map<String, String>` in favor of `Map<String, StreamController>` where the String is the id?

**Comment by clangenb** [comment]
> The previous implementation supposed that a `subscriptionId` was unique only within each `method` but that seems to be incorrect and they are unique globally. Do you think we could simplify that and remove the `Map<String, String>` in favor of `Map<String, StreamController>` where the String is the id?

I was thinking the same thing, but then we have no way of knowing to which methods we have already subscribed to, and hence we can't prevent double subscription then. I think we want to prevent it, so that potential users of the crate can't accidentally create toons of subscriptions for the same thing.

**Comment by leonardocustodio** [comment]
Although I understand that reusing the same subscription could be helpful for the developer. I'm not really sure we can say that there will be no use case where they will not want to subscribe multiple times to the same thing.
This is from `polkadot-js` https://github.com/polkadot-js/api/blob/a22a111f7228e80e03bc75298347dbd184c5630b/packages/rpc-provider/src/ws/index.ts#L533 the code is a bit confusing tbh but doesn't seem they handle that.

**Comment by clangenb** [comment]
Yeah, I totally understand your reasoning, my idea was that the as long as the `params` of the subscription are the same, we'd not want to open another subscription, this would also apply to the tx, as there won't be the same tx as the nonce is increasing. 

Regardless, I am not sure yet if my logic is somewhere flawed. So I will happily change it in a way that allows for double subscription. 👍

File: packages/polkadart/lib/provider.dart (hunk 1 above)
Comment (clangenb) [reply packages/polkadart/lib/provider.dart:189]: Alright, I think I am a bit short on time next week. Do you mind if we just keep the print statements as comments for now and merge this PR, and we introduce proper logging in a separate PR in the future?

**Comment by clangenb** [comment]
From my point of view, ready to merge!

**Review by leonardocustodio — APPROVED** [review]
Seems good to me, nice job 👍
